kitsune-soc/kitsune

Cargo.lock
Cargo.toml
kitsune-http-client/Cargo.toml
kitsune-http-client/README.md
kitsune-http-client/src/lib.rs
kitsune-http-client/src/util.rs
kitsune-http-client/tests/basic.rs
kitsune-http-client/tests/json.rs
kitsune-search/Cargo.toml
kitsune/Cargo.toml
kitsune/src/activitypub/deliverer.rs
kitsune/src/activitypub/fetcher.rs
kitsune/src/error.rs
kitsune/src/webfinger.rs
migration/Cargo.toml

Replace reqwest with a custom HTTP client abstraction

---

Cargo.lock
kitsune-http-client/Cargo.toml
kitsune-http-client/src/lib.rs
kitsune-http-signatures/Cargo.toml
kitsune-http-signatures/src/error.rs
kitsune-http-signatures/src/header.rs
kitsune-http-signatures/src/lib.rs
kitsune-http-signatures/tests/all_headers.rs
kitsune-http-signatures/tests/basic.rs
kitsune-http-signatures/tests/sign.rs
kitsune/Cargo.toml
kitsune/src/http/extractor.rs

This PR slightly changes the API of the `kitsune-http-signatures` crate

Small HTTP signature changes

---

Cargo.lock
kitsune-http-client/Cargo.toml
kitsune-http-signatures/Cargo.toml
kitsune-search/Cargo.toml
kitsune-search/src/grpc/service/index.rs
kitsune-search/src/grpc/service/search.rs
kitsune-type/Cargo.toml
kitsune/Cargo.toml
kitsune/src/activitypub/deliverer.rs
kitsune/src/activitypub/fetcher.rs
kitsune/src/cache.rs
kitsune/src/resolve/inbox.rs
kitsune/src/resolve/post.rs
kitsune/src/search.rs
kitsune/src/webfinger.rs
post-process/Cargo.toml

This PR adds some more instrumentation to the services.  
Namely it instruments more functions using tracing and adds metrics to functions using the `autometrics` crate.

Add some more instrumentation

---

kitsune-cli/src/role.rs
kitsune-db/migration/src/m20220101_000001_create_table.rs
kitsune-db/migration/src/m20221121_210920_create_oauth2_tables.rs
kitsune-db/src/entity/accounts.rs
kitsune-http-signatures/src/lib.rs
kitsune/src/activitypub/fetcher.rs
kitsune/src/http/graphql/mod.rs
kitsune/src/http/handler/users/inbox.rs
kitsune/src/mapping/mastodon.rs
kitsune/src/service/post.rs
kitsune/src/service/user.rs

Database optimisations

---

Cargo.lock
Cargo.toml
kitsune-messaging/Cargo.toml
kitsune-messaging/examples/simple.rs
kitsune-messaging/examples/simple_redis.rs
kitsune-messaging/examples/simple_tokio_broadcast.rs
kitsune-messaging/src/lib.rs
kitsune-messaging/src/redis.rs
kitsune-messaging/src/tokio_broadcast.rs
kitsune-search/Cargo.toml
kitsune-search/proto/Cargo.toml
kitsune/Cargo.toml
kitsune/src/error.rs
kitsune/src/event/mod.rs
kitsune/src/event/post.rs
kitsune/src/event/status.rs
kitsune/src/http/handler/users/inbox.rs
kitsune/src/lib.rs
kitsune/src/main.rs
kitsune/src/mapping/mastodon/mod.rs
kitsune/src/mapping/mod.rs
kitsune/src/service/post.rs
kitsune/src/state.rs

Implement event system

---

kitsune/src/http/handler/mastodon/api/v2/search.rs
kitsune/src/service/search.rs

When trying to get this service to run on Shuttle, I noticed that the search service uses protobuf definitions outside of the search module. 
This PR replaces these protobuf definitions with basically equivalent definitions that live inside the search module instead, to have a clean abstraction over the gRPC service.

Clean split between search module and gRPC

---

kitsune/src/config.rs
kitsune/src/http/handler/users/followers.rs
kitsune/src/http/handler/users/following.rs
kitsune/src/http/handler/users/mod.rs
kitsune/src/http/handler/users/outbox.rs
kitsune/src/http/handler/well_known/nodeinfo.rs
kitsune/src/http/page.rs
kitsune/src/main.rs
kitsune/src/mapping/mastodon/mod.rs
kitsune/src/mapping/mastodon/sealed.rs
kitsune/src/service/attachment.rs
kitsune/src/service/mod.rs
kitsune/src/service/post.rs
kitsune/src/service/url.rs
kitsune/src/service/user.rs
kitsune/src/state.rs

Add URL construction service

---

kitsune-db/migration/src/m20221213_214258_create_mention_table.rs
kitsune-db/src/entity/posts_mentions.rs
kitsune-type/src/ap/helper.rs
kitsune-type/src/ap/mod.rs
kitsune-type/src/ap/object.rs
kitsune/src/activitypub/fetcher.rs
kitsune/src/activitypub/mod.rs
kitsune/src/error.rs
kitsune/src/http/handler/mastodon/api/v2/search.rs
kitsune/src/http/handler/oauth/token.rs
kitsune/src/http/handler/users/inbox.rs
kitsune/src/mapping/activitypub/activity.rs
kitsune/src/mapping/activitypub/object.rs
kitsune/src/resolve/post.rs
kitsune/src/sanitize.rs
kitsune/src/service/post.rs

Rework ActivityPub types

---

config.example.dhall
kitsune/config/types.dhall
kitsune/config/types/instance.dhall
kitsune/src/config.rs
kitsune/src/http/handler/mastodon/api/v1/instance.rs
kitsune/src/main.rs
kitsune/src/service/instance.rs
kitsune/src/service/mod.rs
kitsune/src/service/post.rs
kitsune/src/state.rs

Add instance configuration options

---

config.example.dhall
kitsune-db/src/lib.rs
kitsune/config/types.dhall
kitsune/config/types/database.dhall
kitsune/src/config.rs
kitsune/src/main.rs

Configurable database parameters

---

config.example.dhall
kitsune/config/types.dhall
kitsune/config/types/search.dhall
kitsune/config/types/search/kitsune.dhall
kitsune/src/config.rs
kitsune/src/main.rs
kitsune/src/service/search/grpc.rs
kitsune/src/service/search/mod.rs
kitsune/src/service/search/sql.rs

Add SQL-based search service

---

.github/workflows/rust.yml

Experiments to speed up the CI a bit

CI speed experiments

---

.env
README.md

Link to new documentation

---

kitsune-db/migration/src/m20220101_000001_create_table.rs
kitsune-db/src/entity/users.rs
kitsune/src/http/handler/oidc/callback.rs
kitsune/src/service/oidc.rs
kitsune/src/service/user.rs

Add OIDC ID column to database

---

post-process/grammar/post.pest
post-process/tests/input/mention/full_post_2
post-process/tests/input/mention/full_post_3
post-process/tests/snapshots/mention__parse_mention@full_post_1.snap
post-process/tests/snapshots/mention__parse_mention@full_post_2.snap
post-process/tests/snapshots/mention__parse_mention@full_post_3.snap

Fix issue with `post-process`

---

kitsune/src/http/handler/mastodon/api/v1/accounts/follow.rs
kitsune/src/http/handler/mastodon/api/v1/accounts/lookup.rs
kitsune/src/http/handler/mastodon/api/v1/accounts/mod.rs
kitsune/src/http/handler/users/mod.rs
kitsune/src/http/openapi.rs
kitsune/src/main.rs
kitsune/src/resolve/post.rs
kitsune/src/service/account.rs

Adds support for the `/api/v1/accounts/lookup` API endpoint

Add Mastodon lookup API

---

Cargo.lock
kitsune/Cargo.toml
kitsune/src/http/extractor/signed_activity.rs

Support Ed25519 HTTP signatures

---

kitsune-db/migration/src/lib.rs
kitsune-db/migration/src/m20220101_000001_create_table.rs
kitsune-db/migration/src/m20230416_200210_create_home_timeline_indices.rs
kitsune/src/service/instance.rs
kitsune/src/service/timeline.rs

This PR fixes the aggregation of the home timeline and adds some indices to speed up the aggregation of the home timeline (according to the PostgreSQL execution plan)

Fix home timeline

---

Cargo.lock
kitsune-search/Cargo.toml
kitsune-search/tests/common.rs
kitsune-storage/Cargo.toml
kitsune-storage/src/fs.rs

The `tempdir` functionality has been merged into `tempfile`

Remove `tempdir` dependency

---

kitsune/src/http/handler/users/followers.rs
kitsune/src/http/handler/users/following.rs
kitsune/src/http/handler/users/mod.rs
kitsune/src/http/handler/users/outbox.rs
kitsune/src/http/handler/well_known/webfinger.rs
kitsune/src/http/page.rs
kitsune/src/job/deliver/accept.rs
kitsune/src/mapping/activitypub/activity.rs
kitsune/src/mapping/activitypub/object.rs
kitsune/src/mapping/mastodon/sealed.rs
kitsune/src/resolve/post.rs
kitsune/src/service/account.rs
kitsune/src/service/url.rs
kitsune/src/service/user.rs
kitsune/src/util.rs

**Breaking change**
This updates the paths to the actors to look like `/users/[User ID]` instead of `/users/[Username]`

Use UUID in user path

---

flake.nix
kitsune/src/http/mod.rs

Allows building Kitsune via `nix build .` (and `nix build .#search`, etc.)

Build support via nix

---

kitsune-fe/src/components/Forms.vue

This fixes issue #203 by
* Set up color attribute (white) on the registration forms CSS style.

Add white text colour attribute on registration form style

---

config.example.dhall
kitsune/Cargo.toml
kitsune/config/types/server.dhall
kitsune/src/config.rs
kitsune/src/http/mod.rs

This PR adds the `CatchPanicLayer` and the `TimeoutLayer` with a configurable timeout

Add additional layers

---

README.md

With the launch of the small dev server (https://dev.joinkitsune.org), we were able to verify that some additional things are working against actual ActivityPub implementations (mainly Mastodon, really)

Update "State of federation" section

---

kitsune/src/http/handler/oauth/authorize.rs

Return 401 instead of 404 when user is not found

---

kitsune/src/activitypub/fetcher.rs

This fixes issue #223 
Closes #223

Do not try to update account if user does not have profile image and header image

---

.github/workflows/rust.yml
Cargo.lock
kitsune/Cargo.toml
kitsune/src/error.rs
kitsune/src/http/graphql/mod.rs
kitsune/src/http/handler/mod.rs
kitsune/src/http/handler/oauth/authorize.rs
kitsune/src/http/handler/users/inbox.rs
kitsune/src/http/mod.rs
kitsune/src/job/mod.rs
kitsune/src/lib.rs
kitsune/src/main.rs
kitsune/src/service/mod.rs
kitsune/src/service/search/mod.rs
kitsune/src/state.rs

Mainly gets rid of the `handlebars` dependency and puts a bunch of things behind feature flags to make the most minimal binary even smaller

Minor size adjustments

---

kitsune-type/src/ap/actor.rs
kitsune-type/src/ap/mod.rs
kitsune-type/src/ap/object.rs
kitsune/src/activitypub/fetcher.rs
kitsune/src/activitypub/mod.rs
kitsune/src/http/handler/mastodon/api/v2/search.rs
kitsune/src/http/handler/users/inbox.rs
kitsune/src/mapping/activitypub/object.rs

This PR intends to fix the federation with PeerTube and introduce basic federation with services such as Lemmy.

Better ActivityPub compatibility

---

kitsune-db/src/json.rs

Skip the `serde_json::Value` step when de-/serialising via the JSON wrapper from JSONB values

Skip `serde_json::Value` step

---

contrib/kitsune.service
system-md-example.service

I added a systemd service example file.
I dont know how/if you can have comments in a .service files so I just did a bit of DIY....
I dont know how to(trying to figure it out but ill probably go to bed first) add files to the left sidebar properly, but if you make a page for basic systemd usage ill fill it out.

Added service example file

---

Cargo.lock
crates/kitsune-core/src/service/account.rs
crates/kitsune-core/src/service/post.rs
crates/kitsune-core/src/service/timeline.rs
crates/kitsune-db/Cargo.toml
crates/kitsune-db/src/post_permission_check.rs
kitsune/src/http/graphql/mutation/post.rs
kitsune/src/http/handler/mastodon/api/v1/statuses/mod.rs
kitsune/src/http/handler/mastodon/api/v1/statuses/reblog.rs
kitsune/src/http/handler/mastodon/api/v1/statuses/unreblog.rs
kitsune/src/http/handler/users/inbox.rs

Replaces some more `derive-builder` usage with `typed-builder`

Extend `typed-builder` usage

---

Cargo.lock
kitsune-job-runner/Cargo.toml
kitsune-job-runner/src/main.rs
kitsune-search-server/Cargo.toml
kitsune-search-server/src/main.rs
kitsune/Cargo.toml
kitsune/src/main.rs

Closes #323 
The [`mimalloc`](https://github.com/purpleprotocol/mimalloc_rust) crate removed their custom alignment checks, fixing the unsoundness in their implementation.

Replace jemalloc with mimalloc

---

kitsune/src/http/openapi.rs

Add `Timestamp` swagger type

---

crates/kitsune-core/src/service/post.rs
kitsune/src/http/handler/mastodon/api/v1/statuses/favourited_by.rs
kitsune/src/http/handler/mastodon/api/v1/statuses/mod.rs
kitsune/src/http/handler/mastodon/api/v1/statuses/reblogged_by.rs

https://github.com/kitsune-soc/kitsune/issues/304

See who boosted/favourited a post in mastodon API

---

Cargo.lock
crates/kitsune-core/Cargo.toml
crates/kitsune-core/src/lib.rs
crates/kitsune-storage/Cargo.toml
crates/kitsune-storage/examples/s3.rs
crates/kitsune-storage/src/s3.rs

This got rid of 27 dependencies and improved the build time by ~20 seconds on my machine
Closes #371

Replace `aws-sdk-s3` with `rusty-s3`

---

Cargo.lock
Cargo.toml
config.example.toml
crates/kitsune-config/src/lib.rs
crates/kitsune-messaging/Cargo.toml
crates/kitsune-observability/Cargo.toml
crates/kitsune-observability/src/lib.rs
kitsune-cli/Cargo.toml
kitsune-job-runner/Cargo.toml
kitsune/Cargo.toml
lib/athena/Cargo.toml

This PR adds the following configurability: 
1. Transport configurability: HTTP or gRPC 
2. Endpoint configurability: Separate endpoints for traces and metrics

OpenTelemetry configurability

---

crates/kitsune-core/src/service/user.rs
kitsune/src/http/handler/oidc/callback.rs

Force registration in OIDC handler

---

config.example.toml
crates/kitsune-config/src/lib.rs
crates/kitsune-core/src/lib.rs
crates/kitsune-core/src/service/attachment.rs
crates/kitsune-core/src/service/user.rs

Add configuration option for non-ASCII usernames

---

README.md
docs/src/configuring/instance.md
docs/src/running/basic-configuration.md

Add documentation about `allow-non-ascii-usernames`

---

Cargo.lock
crates/kitsune-util/Cargo.toml
crates/kitsune-util/src/sanitize.rs

Replace `ammonia` with `bubble-bath`

---

kitsune-fe/package.json
kitsune-fe/yarn.lock

Closes #450 
@yonas could you check whether that fixes the build on your FreeBSD machine? I don't really have quick access to a FreeBSD install right now.

Use WASM compiled `rollup`

---

kitsune/src/main.rs

This is an old diagnostic that hasn't been relevant ever since we switched to only supporting PostgreSQL.  
Right now we are running into issues with that diagnostic (since it is obscuring the actual backtrace; see #452 ).
Instead of going through the effort of porting this, I'm simply removing it.

Remove old diagnostic

---

Cargo.lock
crates/kitsune-activitypub/Cargo.toml
crates/kitsune-cache/Cargo.toml
crates/kitsune-db/Cargo.toml
crates/kitsune-oidc/Cargo.toml
crates/kitsune-service/Cargo.toml
crates/kitsune-type/Cargo.toml
kitsune-cli/Cargo.toml
kitsune-job-runner/Cargo.toml
kitsune/Cargo.toml
kitsune/src/http/mod.rs
kitsune/src/lib.rs
kitsune/src/main.rs
kitsune/src/signal.rs

Add graceful shutdown functionality

---

Cargo.lock
Cargo.toml
crates/kitsune-config/src/database.rs
crates/kitsune-db/Cargo.toml
crates/kitsune-db/src/lib.rs
crates/kitsune-db/src/tls.rs
crates/kitsune-test/Cargo.toml
crates/kitsune-test/src/lib.rs
docs/src/configuring/database.md
kitsune-cli/Cargo.toml
kitsune-cli/src/config.rs
kitsune-cli/src/main.rs
kitsune-job-runner/src/main.rs
kitsune/src/main.rs

Closes #474 
This capability is equivalent to `sslmode=verify-full` when using `libpq`
TODO:

Add ability to connect to database with TLS

---

.github/workflows/typo-check.yml
CONTRIBUTING.md
README.md
_typos.toml
crates/kitsune-captcha/README.md
crates/kitsune-captcha/src/lib.rs
crates/kitsune-db/migrations/2023-05-19-192931_initial_tables/up.sql
crates/kitsune-db/src/pool.rs
crates/kitsune-mastodon/src/sealed.rs
crates/kitsune-messaging/src/lib.rs
docs/src/configuring/storage.md
kitsune-fe/src/graphql/types/graphql.ts
lib/speedy-uuid/src/lib.rs
module.nix

This PR restructures the README and adds an action that checks for typos in the source code

README restructure and typo check

---

Cargo.lock
crates/kitsune-activitypub/src/error.rs
crates/kitsune-activitypub/src/fetcher/actor.rs
crates/kitsune-activitypub/src/fetcher/emoji.rs
crates/kitsune-activitypub/src/lib.rs
crates/kitsune-config/Cargo.toml
crates/kitsune-db/Cargo.toml
crates/kitsune-db/src/error.rs
crates/kitsune-db/src/lib.rs
crates/kitsune-db/src/pool.rs
crates/kitsune-email/src/error.rs
crates/kitsune-embed/src/lib.rs
crates/kitsune-mastodon/src/error.rs
crates/kitsune-search/src/error.rs
crates/kitsune-service/src/error.rs
crates/kitsune-service/src/post/mod.rs
crates/kitsune-service/src/user.rs
kitsune-cli/Cargo.toml
kitsune-job-runner/Cargo.toml
kitsune/Cargo.toml
kitsune/src/error.rs
kitsune/src/oauth2/issuer.rs
lib/athena/Cargo.toml
lib/post-process/Cargo.toml
lib/tower-http-digest/Cargo.toml
lib/tower-stop-using-brave/Cargo.toml

Didn't migrate for Redis since migration bikeshedding for that is already done in #485

Migrate away from Deadpool to BB8 for database connections

---

.gitignore
Cargo.lock
config.example.toml
crates/kitsune-config/Cargo.toml
crates/kitsune-config/src/server.rs
kitsune/Cargo.toml
kitsune/src/http/mod.rs
kitsune/templates/fallback-fallback.html

<https://corteximplant.com/@0x0/112224860949962641>

NGINX-looking fallback fallback, small improvements

---

Cargo.lock
Cargo.toml
crates/kitsune-wasm-mrf/Cargo.toml
lib/fast-cjson/Cargo.toml
lib/fast-cjson/tests/proptest.rs
lib/mrf-manifest/Cargo.toml
lib/mrf-tool/Cargo.toml
website/package-lock.json
website/package.json

Fix miscellaneous stuff
- Disable the proptest
- Remove the olpc-cjson patch and use the new published version
- Bump astro to fix security advisory

Fix miscellaneous things

---

Cargo.lock
crates/kitsune-activitypub/Cargo.toml
crates/kitsune-db/Cargo.toml
crates/kitsune-derive/impl/Cargo.toml
crates/kitsune-http-client/Cargo.toml
crates/kitsune-observability/Cargo.toml
crates/kitsune-oidc/Cargo.toml
crates/kitsune-oidc/src/lib.rs
crates/kitsune-oidc/src/state/mod.rs
crates/kitsune-oidc/src/state/store/in_memory.rs
crates/kitsune-service/Cargo.toml
crates/kitsune-test/Cargo.toml
crates/kitsune-util/Cargo.toml
crates/kitsune-webfinger/Cargo.toml
flake.lock
lib/fast-cjson/Cargo.toml
lib/masto-id-convert/Cargo.toml
lib/speedy-uuid/Cargo.toml

- Update cargo
- Update flake
- Add in-memory store tests for OIDC

Miscellaneous stuff

---

Cargo.lock
Cargo.toml
kitsune/src/http/router.rs
lib/cursiv/src/service.rs
lib/flashy/Cargo.toml
lib/flashy/src/lib.rs
lib/flashy/tests/basic.rs

This PR reduces the allocations in the flash impl by rolling our own signing via BLAKE3.
It also fixes the route definitions I forgot to update when upgrading axum

Less allocations in flash impl
