Cargo.lock
kitsune-db/Cargo.toml
kitsune-db/src/lib.rs
kitsune-search/Cargo.toml
kitsune/Cargo.toml
kitsune/src/activitypub/fetcher.rs
kitsune/src/cache.rs
kitsune/src/error.rs
kitsune/src/http/graphql/mutation/post.rs
kitsune/src/http/graphql/types/account.rs
kitsune/src/http/handler/mastodon/api/v1/statuses/mod.rs
kitsune/src/http/handler/mastodon/api/v2/search.rs
kitsune/src/http/handler/oauth/authorize.rs
kitsune/src/http/handler/oauth/token.rs
kitsune/src/http/handler/users/followers.rs
kitsune/src/http/handler/users/following.rs
kitsune/src/http/handler/users/outbox.rs
kitsune/src/lib.rs
kitsune/src/main.rs
kitsune/src/mapping/activitypub/object.rs
kitsune/src/mapping/mastodon.rs
kitsune/src/resolve/post.rs
kitsune/src/service/mod.rs
kitsune/src/service/post.rs
kitsune/src/service/search.rs
kitsune/src/state.rs
kitsune/src/webfinger.rs

This PR moves post related logic into a service structure.  
The goal of this is to deduplicate a bunch of logic that is shared between the GraphQL and the Mastodon API.

Abstract into post service

---

Cargo.lock
kitsune-search/proto/Cargo.toml
kitsune-search/proto/build.rs

When exploring Shuttle compatibility, we noticed that there was no protobuf compiler installed in their build environment and that there is also no way to install one.  
This PR adds a feature gated behind `vendored-protoc` on the `kitsune-search-proto` crate that uses a vendored binary from the `protoc-bin-vendored` crate to build the proto definitions with.
This isn't intended as a permanent addition, but as an optional feature it doesn't hurt to have it.
Related to #78

Build feature for using a vendored protobuf compiler

---

kitsune-type/src/ap/object.rs
kitsune-type/src/webfinger.rs
kitsune/src/activitypub/fetcher.rs
kitsune/src/http/handler/users/inbox.rs
kitsune/src/http/handler/well_known/webfinger.rs
kitsune/src/mapping/activitypub/object.rs
kitsune/src/sanitize.rs

Fixes:
- Missing `type` field in Webfinger response
- The post subject field is actually called `summary`

Fix small ActivityPub incompatibilities

---

Cargo.lock
kitsune-http-client/Cargo.toml
kitsune-search/Cargo.toml
kitsune-search/proto/Cargo.toml
kitsune-search/src/grpc/service/index.rs
kitsune-search/src/grpc/service/search.rs
kitsune-search/src/search/schema.rs
kitsune/Cargo.toml
kitsune/src/http/mod.rs
kitsune/src/service/search.rs
proto/search/search.proto

Currently the results are ordered by their Levenshtein distance, i.e. the closer the search query matches the text, the higher it ranks.  
I'm not sure how Mastodon handles it, whether they do chronological handling, too. 
We should closely imitate Mastodon in terms of search result ordering, otherwise we might break expectations some clients have.
It would be great if someone on an instance with full-text search could chime in an tell me how Mastodon orders the results (my instance doesn't have full-text search for posts enabled)

Make search results chronologically ordered

---

kitsune/src/activitypub/fetcher.rs
kitsune/src/http/handler/mastodon/api/v2/search.rs

You can now paste URLs into the search bar of your Mastodon client, and Kitsune will attempt to fetch the post/account

Add ability to import posts and accounts via the search

---

kitsune/src/activitypub/fetcher.rs
kitsune/src/cache.rs
kitsune/src/http/handler/mastodon/api/v2/search.rs
kitsune/src/mapping/mastodon/mod.rs
kitsune/src/resolve/post.rs
kitsune/src/service/post.rs
kitsune/src/service/search.rs
kitsune/src/webfinger.rs

Some of the types inside Kitsune were highly parameterised using generic types. This was originally done for testability.
Recently the testability shifted from using generics to using dynamic dispatch since using generic parameters with Axum's `State` extractor is pretty difficult.  
The generic parameters defaulted to their Arc'd counterparts as a quick fix.  
This PR removes the generic parameters since they aren't really needed anymore to provide testability

Simplify the usage of generics

---

Cargo.lock
config.example.dhall
flake.nix
kitsune/Cargo.toml
kitsune/config/types.dhall
kitsune/config/types/search.dhall
kitsune/config/types/search/meilisearch.dhall
kitsune/src/config.rs
kitsune/src/error.rs
kitsune/src/main.rs
kitsune/src/service/search/grpc.rs
kitsune/src/service/search/meilisearch.rs
kitsune/src/service/search/mod.rs
kitsune/src/service/search/sql.rs

Closes #136 
The support is gated behind the `meilisearch` feature flag. This is because the SDK uses `ishac` as their HTTP client which somewhere in the dependency tree pulls in a crate that requires installed OpenSSL development libraries.  
Due to this required native dependency this feature is explicitly *opt-in*

Add basic Meilisearch support

---

Cargo.lock
kitsune/Cargo.toml
kitsune/src/activitypub/fetcher.rs
kitsune/src/http/extractor/signed_activity.rs
kitsune/src/http/graphql/mutation/auth.rs
kitsune/src/http/handler/mastodon/api/v1/accounts/statuses.rs
kitsune/src/http/handler/mastodon/api/v1/apps.rs
kitsune/src/http/handler/mastodon/api/v1/media.rs
kitsune/src/http/handler/mastodon/api/v1/timelines/home.rs
kitsune/src/http/handler/mastodon/api/v1/timelines/public.rs
kitsune/src/http/handler/oauth/authorize.rs
kitsune/src/http/handler/oidc/callback.rs
kitsune/src/http/handler/users/mod.rs
kitsune/src/http/handler/users/outbox.rs
kitsune/src/main.rs
kitsune/src/mapping/mastodon/mod.rs
kitsune/src/mapping/mod.rs
kitsune/src/resolve/post.rs
kitsune/src/service/account.rs
kitsune/src/service/attachment.rs
kitsune/src/service/instance.rs
kitsune/src/service/oauth2.rs
kitsune/src/service/oidc.rs
kitsune/src/service/post.rs
kitsune/src/service/timeline.rs
kitsune/src/service/url.rs
kitsune/src/service/user.rs

The usage of the builder pattern for passing options between services is nice but the runtime validation of whether all the parameters are present is a potential source of mistakes.
`typed-builder` utilises the typestate pattern to produce compile-time validated builders. This will make future refactors of services and their parameters easier

Replace a bunch of `derive_builder` usage with `typed-builder`

---

Cargo.lock
kitsune-messaging/Cargo.toml
kitsune-messaging/src/redis.rs

- Demultiplexer now uses `ahash` as the hasher for the mapping
- Introduced macro for error handling

Minor Redis changes

---

README.md
kitsune-type/src/ap/collection.rs
kitsune-type/src/ap/helper.rs
kitsune-type/src/ap/mod.rs
kitsune-type/src/ap/object.rs
kitsune/src/activitypub/deliverer.rs
kitsune/src/activitypub/fetcher.rs
kitsune/src/http/extractor/signed_activity.rs
kitsune/src/http/handler/users/inbox.rs
kitsune/src/mapping/activitypub/activity.rs
kitsune/src/mapping/activitypub/object.rs
kitsune/src/service/federation_filter.rs

The current layout of the ActivityPub types felt a bit off. This PR changes how they are represented as structs.  
While the new structure does introduce some repeated field names, I think it's still easier to reason about than the previous one.

ActivityPub type rework

---

kitsune-type/src/mastodon/status.rs
kitsune/src/http/handler/mastodon/api/v1/accounts/statuses.rs
kitsune/src/http/handler/mastodon/api/v1/statuses/favourite.rs
kitsune/src/http/handler/mastodon/api/v1/statuses/mod.rs
kitsune/src/http/handler/mastodon/api/v1/statuses/unfavourite.rs
kitsune/src/http/handler/mastodon/api/v1/timelines/home.rs
kitsune/src/http/handler/mastodon/api/v1/timelines/public.rs
kitsune/src/http/handler/mastodon/api/v2/search.rs
kitsune/src/mapping/mastodon/mod.rs
kitsune/src/mapping/mastodon/sealed.rs

Populate `reblogged` and `favourited` properties in Mastodon status entities

---

kitsune/src/http/handler/users/inbox.rs
kitsune/src/job/deliver/accept.rs
kitsune/src/job/deliver/mod.rs
kitsune/src/job/mod.rs

ActivityPub requires the delivery of an `Accept` activity as a reply to a `Follow`. These weren't sent out yet.  
This PR adds a job to deliver accept activities and enqueues such a job inside the inbox when user is unlocked.

Fix follows on unlocked accounts

---

kitsune/src/activitypub/fetcher.rs
kitsune/src/http/handler/users/inbox.rs
kitsune/src/service/instance.rs
kitsune/src/service/post.rs

Small fixes for SQLite
1. The select was broken. We called `select_only` but no column to select
2. A transaction in SQLite locks the whole database, then we tried to enqueue the job via a separate database connection. This will obviously fail after the timeout since this would be a double lock. To fix this, I simply moved the job enqueueing outside of the transaction.  
I think this is fine because the post is in a complete state. It not being federated isn't really a concern of the transaction.
Thanks to `s4if` on Matrix for reporting these issues

SQLite fixes

---

kitsune-db/migration/src/m20220101_000001_create_table.rs

This invariant is now covered by the unique index over the username and domain. Done in preparation for #179

Remove the unique requirement from the `username` column

---

.cargo/config.toml
flake.nix

This PR enables the `aes` CPU feature. We still need to find a way to conditionally set the `target_cpu` flag in the Nix build step, to enable CPU specific optimisations

Enable CPU features

---

kitsune-http-client/src/lib.rs
kitsune-http-client/tests/basic.rs
kitsune/src/activitypub/fetcher.rs

With some servers, our HTTP client will get a "400 Bad Request" in response with HTTP/2 enabled.  
Not yet entirely sure why, but to mitigate this for now disabling HTTP/2 should work. 
Issue tracked in #225

Disable HTTP/2

---

kitsune-http-client/src/lib.rs

Apparently NGINX doesn't like it when you send the `Host` header inside HTTP/2 requests
Closes #225

Remove the `Host` header

---

kitsune-db/migrations/2023-05-19-192931_initial_tables/down.sql
kitsune-db/migrations/2023-05-19-192931_initial_tables/up.sql
kitsune/src/http/graphql/types/account.rs
kitsune/src/http/handler/mastodon/api/v1/accounts/statuses.rs
kitsune/src/http/handler/mastodon/api/v1/timelines/home.rs
kitsune/src/http/handler/mastodon/api/v1/timelines/public.rs
kitsune/src/http/handler/users/mod.rs
kitsune/src/http/handler/users/outbox.rs
kitsune/src/job/mod.rs
kitsune/src/service/account.rs
kitsune/src/service/timeline.rs

- Additional indices on the job table
- Limit via the SQL query instead of `.take` on streams
- Order by the k-sortable IDs instead of by the timestamp

Small database-level optimisations

---

Cargo.lock
Cargo.toml
kitsune-db/Cargo.toml
kitsune-db/src/model/job.rs
kitsune/Cargo.toml
kitsune/src/http/page.rs
kitsune/src/job/deliver/accept.rs
kitsune/src/job/deliver/favourite.rs
kitsune/src/job/deliver/follow.rs
kitsune/src/job/deliver/unfavourite.rs
kitsune/src/job/deliver/unfollow.rs
kitsune/src/job/mod.rs
kitsune/src/mapping/activitypub/activity.rs
kitsune/src/mapping/activitypub/object.rs
kitsune/src/mapping/mastodon/sealed.rs
kitsune/src/service/account.rs
kitsune/src/util.rs

Closes #219 
~~Whether this gets merged is still open since it adds a bunch of boxing to get around the higher-ranked lifetime issue.  
There isn't really any other way to get around it since it's a compiler bug~~.
Update: After reading through the "Bogus higher-ranked lifetime error" issue, I attempted a trick to have a small no-op function with trait bounds to hint the `Send` bound to the compiler. That worked and we have now have a solution with 0 additional boxing.

Query pipelining

---

Cargo.lock
Cargo.toml
kitsune-cli/Cargo.toml
kitsune-db/Cargo.toml
kitsune-http-client/Cargo.toml
kitsune-http-signatures/Cargo.toml
kitsune-messaging/Cargo.toml
kitsune-search/Cargo.toml
kitsune-search/proto/Cargo.toml
kitsune-storage/Cargo.toml
kitsune-type/Cargo.toml
kitsune/Cargo.toml
post-process/Cargo.toml

Bump version of all packages to `v0.0.1-pre.1`. The version is also now stored centralised in the workspace manifest for easier bumps in the future.
Just bumping the version, not sure if I'm cutting a release today.

Bump version

---

Cargo.toml
post-process/grammar/post.pest
post-process/tests/input/mixed/mixed_content_2
post-process/tests/snapshots/mixed__mixed_content@mixed_content_1.snap
post-process/tests/snapshots/mixed__mixed_content@mixed_content_2.snap

The URL parser had a bug where it considered HTML following a link (i.e. "https://example.com<\/p>") as part of the link.  
This PR fixes this my marking `<` as a link delimiter.

Fix URL parsing

---

README.md

Many people are maybe not comfortable or willing to create a Matrix account just to join a chat room.  
Since Discord already has a lot of users, I thought this might be an interesting idea to pursue as an alternative chat platform.
Both services are bridged together, so everyone can talk with everyone else.

Add link to a Discord server

---

Cargo.lock
kitsune/Cargo.toml
kitsune/src/lib.rs
kitsune/src/main.rs

`@chpietsch@digitalcourage.social` reported on Mastodon that the error messages Kitsune returned in some instances (namely when passed an SQLite connection string, for which we dropped support last release) were really confusing and frustrating.
This PR adds `anyhow` based error handling for the initialisation function, adds somewhat useful context messages to the errors, and adds special diagnostics for database URLs (to remove confusion).
We will also update the documentation to reflect those database changes.

Improve error messages

---

kitsune/src/activitypub/mod.rs

Currently the insertion into the database fails if a post has two duplicate mentions.  
This can happen when someone posts something like:
```
I really like @kitsune. Check out @kitsune 
```
Some implementations then send an object with the same mention object. This PR just ignores duplicate issues via a `ON CONFLICT NO NOTHING` clause

Ignore duplicate mentions

---

.cargo/config.toml

This could potentially lead to some weird compilation mismatches if the CPU of the machine compiling the code differs from the CPU running the machine, but I'll take my chances here.
Better have working builds for most end-users for now than broken builds for everyone

Add `target-cpu=native` to the RUSTFLAGS

---

Cargo.lock
kitsune/Cargo.toml
kitsune/config/types/instance.dhall
kitsune/src/config.rs
kitsune/src/http/handler/oauth/token.rs
kitsune/src/http/middleware.rs
kitsune/src/http/mod.rs

Some clients send their OAuth credentials as JSON payloads. This against the OAuth2 RFC but alas, we want high compatibility with Mastodon clients.  
This middleware deserialises the body into its DOM representation if the header "Content-Type" is set to "application/json" and reencodes it into the URL-encoded version

Add middleware for handling JSON to OAuth endpoints

---

flake.nix
module.nix
overlay.nix

I use `deploy-rs` for deploying my machines, this is how I use this module with it, with other ways to configure it's likely to be a little different:
Apply the overlay and module to the system before loading its configuration:
```nix
kitsune-test = nixpkgs.lib.nixosSystem {
system = "x86_64-linux";
modules = [
({ ... }: { nixpkgs.overlays = [ kitsune.overlays.default ]; })
kitsune.nixosModules.default
kitsune-test/configuration.nix
];
};
```
Configure postgres, kitsune, caddy:
```nix
services.postgresql = {
enable = true;
initialScript = pkgs.writeText "kitsune-init.sql" ''
CREATE ROLE "kitsune" WITH LOGIN PASSWORD 'kitsune';
CREATE DATABASE "kitsune" WITH OWNER "kitsune"
TEMPLATE template0
LC_COLLATE = "C"
LC_CTYPE = "C";
'';
};
services.kitsune = {
enable = true;
config = {
instance = …
```

Add nixos service module to the flake

---

.cargo/config.toml

Because Intel Core i3 for example does not have them.

Do not assume CPU support for aes instructions

---

.github/workflows/rust.yml

There have been CI failures related to illegal instructions. My guess is that this is because we optimized builds for one very specific CPU in particular and the GitHub actions runners span over multiple different x86 CPU architectures.
This PR optimizes for `x86-64-v3` and no one specific CPU in particular which should hopefully prevent these `SIGILL`s from happening

Build for x86-64-v3 in CI

---

.dockerignore
config.docker.toml
docker-compose.yml
kitsune-search-server/Dockerfile.dev
kitsune-search-server/Dockerfile.prod
kitsune/Dockerfile.dev
kitsune/Dockerfile.prod

Changes include:
- multi-layered build process for docker:
- use cargo chef to gather dependencies into a recipe
- use cargo chef to install said dependencies
- build kitsune
- build frontend
- include the app and frontend files in the final image
This makes it so only the project libraries and binaries are rebuilt after making changes, instead of the whole dependency tree speeding up the build process from around 15m to 3m and saving space.
- docker-compose can now receive the app config as a mounted readonly file, like so
`KITSUNE_CONFIG=/home/user/kitsune/config.docker.toml docker-compose up`
- I made kitsune depend on db and redis in the docker compose stack because otherwise it would sometimes panic if these components haven't properly initialized before the app started

Layered docker images and improved docker-compose deployment

---

Cargo.lock
Cargo.toml
kitsune-cache/Cargo.toml
kitsune-cache/src/in_memory.rs
kitsune-cache/src/lib.rs

As per suggestion of @tesaguri on Matrix, this PR changes the internals of the in-memory cache to use the `moka` library.
This simplifies the code and could deliver some performance improvements (though I haven't verified that)

Update the in-memory cache to use `moka`

---

crates/kitsune-type/src/webfinger.rs
kitsune/src/config.rs
kitsune/src/http/graphql/query/instance.rs
kitsune/src/http/handler/mastodon/api/v1/instance.rs
kitsune/src/http/handler/well_known/webfinger.rs
kitsune/src/lib.rs
kitsune/src/service/url.rs

This adds ~~`instance.webfinger_domain`~~ `instance.webfinger-domain` configuration option to set a custom domain name for the `subject` of local WebFinger resources. See #285 for the background.
The configuration will look like the following:
```toml
[instance]
webfinger-domain = "example.com"
[url]
scheme = "https"
domain = "social.example.com"
```
This example will run the server at `social.example.com` and make the WebFinger handler resolve local actors as `acct:{username}@example.com` instead of `acct:{username}@social.example.com`.
`GET /api/v1/instance` of Mastodon API and its counterpart in GraphQL API is updated to use the new configuration value to make it align with Mastodon's implementation (though Mastodon doesn't provide a GraphQL API. But since the old value can trivially …

Add `webfinger-domain` configuration

---

kitsune/src/http/handler/mastodon/api/v1/statuses/mod.rs

This fixes issue #319 by mapping `Some("")` to `None` in following APIs
* `POST /api/v1/status`
* `PUT /api/v1/status/{id}`

Fix issue #319

---

.github/workflows/rust.yml
.gitignore
flake.lock
flake.nix

Right now we have two split configurations for `backend` which has all dependencies to do backend development and `backend-full` which boots up Redis and PostgreSQL.  
This PR replaces this split configuration with `devenv`. The new workflow looks like this:
```sh
nix develop .#backend --impure
devenv up
```

Use `devenv` for development shells

---

.github/workflows/rust.yml

This allows the `fmt` job to run in parallel with the other jobs and reduces CI execution time by ~1 min.

ci: Remove `needs: fmt` requirements

---

Cargo.lock
Cargo.toml
crates/kitsune-core/Cargo.toml
crates/kitsune-core/build.rs
crates/kitsune-core/src/job/mod.rs
crates/kitsune-core/src/lib.rs
crates/kitsune-search/Cargo.toml
kitsune-job-runner/Cargo.toml
kitsune-job-runner/src/lib.rs
kitsune-job-runner/src/main.rs
kitsune/Cargo.toml
kitsune/build.rs
kitsune/src/http/handler/mastodon/api/v1/notifications/clear.rs
kitsune/src/http/handler/mastodon/api/v1/notifications/dismiss.rs
kitsune/src/http/handler/mastodon/api/v1/statuses/unreblog.rs
kitsune/src/lib.rs
kitsune/src/main.rs

This PR adds a new binary that runs jobs dispatched by the main Kitsune binary.  
The idea behind this is that the running of jobs is something that can be highly parallelised, therefore someone could spin up a single server to handle all the HTTP requests, and ten job runners to handle all the outgoing federation, email delivery, etc.

Dedicated job runner

---

.cargo/config.toml
.github/workflows/rust.yml
Cargo.lock
crates/kitsune-cache/Cargo.toml
crates/kitsune-cache/src/in_memory.rs
crates/kitsune-captcha/Cargo.toml
crates/kitsune-core/Cargo.toml
crates/kitsune-db/Cargo.toml
crates/kitsune-email/Cargo.toml
crates/kitsune-embed/Cargo.toml
crates/kitsune-http-client/Cargo.toml
crates/kitsune-http-signatures/Cargo.toml
crates/kitsune-messaging/Cargo.toml
crates/kitsune-storage/Cargo.toml
crates/kitsune-type/Cargo.toml
flake.lock
kitsune-cli/Cargo.toml
kitsune-job-runner/Cargo.toml
kitsune/Cargo.toml
lib/athena/Cargo.toml
lib/post-process/Cargo.toml

`simd-json` should do runtime feature detection now, meaning we can get rid of the `target-cpu=native` configuration flag

Upgrade dependencies

---

Cargo.lock
crates/kitsune-db/Cargo.toml
crates/kitsune-db/src/error.rs
crates/kitsune-db/src/lib.rs

This PR removes our usage of the custom `diesel_migrations_async` crate, and replaces it with the `diesel_migrations` crate using the new `async-connection-wrapper` feature.

Remove `diesel_migrations_async`

---

crates/kitsune-type/src/mastodon/status.rs
kitsune/src/http/openapi.rs

Relates to https://github.com/kitsune-soc/kitsune/issues/360
I validated the entire schema this time and it turns out that there were still errors with `SmolStr` and `VecDeque` definitions missing + PreviewCard and PreviewType not added to the list.

More swagger fixes

---

Cargo.lock
Cargo.toml
crates/kitsune-config/Cargo.toml
crates/kitsune-db/Cargo.toml
crates/kitsune-messaging/Cargo.toml
kitsune-job-runner/Cargo.toml
lib/athena/Cargo.toml

This PR patches the `isolang` dependency to use the latest Git version.
The Git version includes a fix that drastically improves the compile times, and therefore gets rid of our biggest "timewaster" during compilation.

Patch `isolang` dependency

---

Cargo.lock
Cargo.toml
lib/masto-id-convert/Cargo.toml
lib/masto-id-convert/src/lib.rs

This PR removes the as unsound marked `lexical` dependency

Remove unsound `lexical` dependency

---

docker-compose.yml

Updated `docker-compose.yaml`
I have adjusted the start command so that it also executes the config that is mapped.
Additionally I have adjusted the quotation marks. If we use double quotes in the port, we should use them everywhere.

fix: docker-compose start command

---

.vscode/settings.json
Cargo.lock
crates/kitsune-cache/Cargo.toml
crates/kitsune-captcha/Cargo.toml
crates/kitsune-core/Cargo.toml
crates/kitsune-core/src/activitypub/fetcher.rs
crates/kitsune-core/src/activitypub/mod.rs
crates/kitsune-core/src/lib.rs
crates/kitsune-core/src/resolve/post.rs
crates/kitsune-core/src/service/mod.rs
crates/kitsune-core/src/service/post.rs
crates/kitsune-core/src/service/search.rs
crates/kitsune-core/src/state.rs
crates/kitsune-db/Cargo.toml
crates/kitsune-http-client/Cargo.toml
crates/kitsune-messaging/Cargo.toml
crates/kitsune-search/src/lib.rs
crates/kitsune-search/src/meilisearch.rs
crates/kitsune-search/src/sql.rs
crates/kitsune-type/Cargo.toml
kitsune/Cargo.toml
kitsune/src/http/handler/mastodon/api/v2/search.rs
kitsune/src/http/handler/users/inbox.rs
kitsune/src/state.rs
lib/athena/Cargo.toml

This PR restructures the search service in the following way:
- `kitsune_search` is now considered a *search backend* abstraction
- `kitsune_core` gets a new service: `SearchService`
- This new service is only there to query the service and to do some resolving
- It resolves posts and accounts by their URLs
The new structure should also enable some nicer query pipelining and will make it easier to keep the feature parity between the Mastodon and (eventual) GraphQL search on the same level.

Restructure search logic

---

Cargo.lock
lib/masto-id-convert/Cargo.toml
lib/masto-id-convert/src/lib.rs

After:
```
process ASCII 110368129515784116
time:   [8.4860 ns 8.5083 ns 8.5317 ns]
Found 2 outliers among 100 measurements (2.00%)
1 (1.00%) low mild
1 (1.00%) high mild
```
Before:
```
process ASCII 110368129515784116
time:   [10.923 ns 10.946 ns 10.990 ns]
change: [+27.961% +28.231% +28.525%] (p = 0.00 < 0.05)
Performance has regressed.
Found 8 outliers among 100 measurements (8.00%)
3 (3.00%) high mild
5 (5.00%) high severe
```

Use a faster crate for ASCII representation parsing

---

Cargo.lock
Cargo.toml
config.example.toml
crates/kitsune-config/src/server.rs
docs/src/SUMMARY.md
docs/src/configuring/deny-brave-browsers.md
kitsune/Cargo.toml
kitsune/src/http/mod.rs
lib/tower-stop-using-brave/Cargo.toml
lib/tower-stop-using-brave/src/lib.rs

To quote the documentation of the option:
> Brave is a company founded by a queerphobic bigot, funded by people such as Peter Thiel.
> You can get pretty much all of Brave's "privacy advantages" with a Firefox + uBlock Origin + DuckDuckGo installation. 
> 
> (Plus, Brave is another Chromium-based browsers. Using Firefox helps diversify the browser landscape at least a little bit)
> 
> When this setting is enabled, all browsers with the Brave User-Agent are redirected to an article explaining the hateful and problematic background of Brave Inc.  
> 
> Since Kitsune is about choice, we give you the ability to simply toggle this functionality off.  
> While we give you that option, you maybe want to keep this option on.
> 
> The reasoning behind this is simple:
> 
> - If people aren't aware …

Add option to redirect Brave browsers to article

---

Cargo.lock
crates/kitsune-activitypub/Cargo.toml
crates/kitsune-cache/Cargo.toml
crates/kitsune-captcha/Cargo.toml
crates/kitsune-db/Cargo.toml
crates/kitsune-http-client/Cargo.toml
crates/kitsune-http-signatures/Cargo.toml
crates/kitsune-http-signatures/src/header.rs
crates/kitsune-http-signatures/src/lib.rs
crates/kitsune-mastodon/Cargo.toml
crates/kitsune-messaging/Cargo.toml
crates/kitsune-oidc/Cargo.toml
crates/kitsune-service/Cargo.toml
crates/kitsune-type/Cargo.toml
crates/kitsune-util/src/lib.rs
crates/kitsune-webfinger/Cargo.toml
flake.nix
kitsune/Cargo.toml
kitsune/src/http/pagination.rs
kitsune/src/lib.rs
kitsune/src/oauth2/registrar.rs
lib/athena/Cargo.toml
lib/masto-id-convert/Cargo.toml
lib/speedy-uuid/Cargo.toml
lib/tower-x-clacks-overhead/Cargo.toml
lib/tower-x-clacks-overhead/src/lib.rs
rust-toolchain.toml

Not really required anymore. Our biggest reason was the usage of "async fn in trait" before it officially released.  
Now that that's landed, we can go back.
Those few improved branch hints we are missing out on won't affect codegen that much for most users.

Revert back to Rust stable

---

Cargo.lock
Cargo.toml
lib/http-signatures/Cargo.toml
lib/http-signatures/src/cavage/easy.rs
lib/http-signatures/src/cavage/safety_check.rs
lib/http-signatures/tests/cavage.rs
lib/tick-tock-mock/Cargo.toml
lib/tick-tock-mock/LICENSE-APACHE-2.0
lib/tick-tock-mock/LICENSE-MIT
lib/tick-tock-mock/README.md
lib/tick-tock-mock/benches/simple_now.rs
lib/tick-tock-mock/src/lib.rs

This PR adds a new crate (`tick-tock-mock`), allowing for intercepting and mocking `SystemTime::now()` and uses the crate throughout `http-signatures`.
It also adds a new test which is a proof-of-concept.  
In the future we can use this to rewind the time to let the tests for RFC test vectors succeed.

Clock mocking for `http-signatures`

---

Cargo.lock
crates/kitsune-activitypub/src/deliverer/mod.rs
crates/kitsune-activitypub/src/lib.rs
crates/kitsune-activitypub/src/mapping/activity.rs
crates/kitsune-activitypub/src/mapping/object.rs
crates/kitsune-activitypub/tests/fetcher/infinite.rs
crates/kitsune-type/Cargo.toml
crates/kitsune-type/src/ap/actor.rs
crates/kitsune-type/src/ap/collection.rs
crates/kitsune-type/src/ap/emoji.rs
crates/kitsune-type/src/ap/helper.rs
crates/kitsune-type/src/ap/mod.rs
crates/kitsune-type/src/ap/object.rs
crates/kitsune-type/src/jsonld/mod.rs
crates/kitsune-type/src/jsonld/serde/first.rs
crates/kitsune-type/src/jsonld/serde/first_id.rs
crates/kitsune-type/src/jsonld/serde/first_ok.rs
crates/kitsune-type/src/jsonld/serde/id.rs
crates/kitsune-type/src/jsonld/serde/id_set.rs
crates/kitsune-type/src/jsonld/serde/mod.rs
crates/kitsune-type/src/jsonld/serde/optional.rs
crates/kitsune-type/src/jsonld/serde/set.rs
kitsune/src/http/extractor/signed_activity.rs

This patch implements some helper functions to translate JSON-LD data structures to something easier to deserialise as Rust data structures, and applies them to the types in `kitsune_type::ap` using the `#[serde(deserialize_with = "…")]` attribute.
This also replaces some usage of the `#[serde(untagged)]` helper types (which basically works by deserialising the full input to a DOM and tries to deserialise it to the variants one by one until succeeds) with the new helpers.
Admittedly, the hand-written `DeserializeSeed` implementations are full of boilerplates (as they generally tend to; Serde's builtin implementations are similarly verbose, for instance), with ~5x  more lines of code than Mitra's `deserialization.rs`. Yet I think they're reasonably modular and maybe efficient (no …

Add helpers to deserialise JSON-LD in a more robust way

---

README.md
assets/sponsor_cleanc.svg

Now, Kitsune is migrating to Woodpecker from GitHub Action.
Since the CI instance is sponsored by CleanC, it is required to attribute them in README.md

Add CI sponsorship attribution

---

Cargo.lock
crates/kitsune-config/src/lib.rs
crates/kitsune-config/src/mrf.rs
crates/kitsune-db/Cargo.toml
crates/kitsune-test/Cargo.toml
crates/kitsune-wasm-mrf/Cargo.toml
crates/kitsune-wasm-mrf/src/cache.rs
crates/kitsune-wasm-mrf/src/lib.rs
docs/src/configuring/mrf.md

Closes #523 
This PR adds an optional cache functionality to Kitsune, where it can cache compiled WASM modules on-disk, improving startup times since we don't have to recompile each module every restart.
To reliably identify modules, we hash them using the BLAKE3 hash function and store them inside a `sled` database.  
Since we store these things on disk, we can assume that they haven't been tampered with by an attacker and therefore won't lead to memory unsafety when we simply load them.
DO NOT touch any of the files inside the cache directory. Just *don't*.  
While yes, Kitsune is written in Rust and therefore doesn't have memory unsafety, if you tamper with the files in there, you might introduce memory unsafety since the data in there are just pieces of executable code.  
Editing …

Cache compiled WASM modules

---

docs/src/running/basic-configuration.md

The format was changed to parse sizes instead of integer number of bytes.

fix(docs): fix config example for max-upload-size.

---

lib/athena/tests/keeper.rs

Since this is kinda vital to the job scheduler and a section where we use unsafe code, I feel like we should test this better.

Add tests for the keeper

---

Cargo.lock
crates/kitsune-captcha/Cargo.toml
crates/kitsune-derive/impl/Cargo.toml
crates/kitsune-s3/Cargo.toml
crates/kitsune-search/Cargo.toml
crates/kitsune-test/Cargo.toml
crates/kitsune-type/Cargo.toml
kitsune/Cargo.toml
lib/athena/Cargo.toml
lib/geomjeungja/Cargo.toml
lib/masto-id-convert/Cargo.toml
lib/mrf-manifest/Cargo.toml
lib/mrf-manifest/src/decode.rs
lib/mrf-tool/Cargo.toml
lib/mrf-tool/src/lib.rs
lib/mrf-tool/tests/manifest.rs
lib/speedy-uuid/Cargo.toml
lib/tower-http-digest/Cargo.toml
lib/tower-stop-using-brave/Cargo.toml
lib/trials/macros/Cargo.toml

I also tried to use it for serializing manifests, but unfortunately it doesn't have the required APIs to handle string escaping. This unfortunately renders it unsuitable for our usecase of having a canonical JSON formatter.

Use sonic-rs for parsing manifests

---

Cargo.lock
Cargo.toml
crates/kitsune-derive/impl/Cargo.toml
crates/kitsune-embed/Cargo.toml
crates/kitsune-embed/src/lib.rs
lib/schaber/Cargo.toml
lib/schaber/LICENSE-APACHE-2.0
lib/schaber/LICENSE-MIT
lib/schaber/src/lib.rs
lib/schaber/tests/basic.rs
lib/schaber/tests/control_flow.rs

We used to use the `scraper` library, which (while it works great) pulls in the `html5ever` crate, which is unnecessary overhead.
We replace the `scraper` library with a small custom built library to scrape our HTML.

Replace `scraper` with a small custom library

---

flake.nix
module.nix

- Use a freeform configuration for the Kitsune module
- Use `buildLayeredImage` instead of `buildImage`
- Use Valkey instead of Redis as the package for the NixOS module

Nix improvements

---

Cargo.lock
Cargo.toml
crates/kitsune-wasm-mrf/Cargo.toml
crates/kitsune-wasm-mrf/src/http_client.rs
crates/kitsune-wasm-mrf/src/kv_storage/mod.rs
crates/kitsune-wasm-mrf/src/logging.rs

This does actually two cool things for us:
1. It gets rid of `async-trait` in wasmtime impls, meaning potential hotloops are now alloc free there, too
2. We now enable the wasmtime `pulley` feature, which is their new Wasm interpreter backend which it falls back to when the architecture isn't supported by Cranelift (for example, `armv7-unknown-linux-gnueabihf`, which is the Raspberry Pi architecture before the Pi 3)
So yeah, this enables us to ship to more platforms, which is pretty cool.

Upgrade cargo dependencies

---

config.example.toml
crates/kitsune-config/src/instance.rs
crates/kitsune-service/src/instance.rs
kitsune/src/lib.rs
website/src/content/docs/configuration/instance.mdx

Add option to randomize instance statistics
